//NORMAL AUTHENTICATION
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// FACEBOOK AUTHENTICATION
export const FACEBOOK_AUTH_START = 'FACEBOOK_AUTH_START';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';

// RIDES ACTIONS
export const FETCH_RIDES_START = 'FETCH_RIDES_START';
export const FETCH_RIDES_FAIL = 'FETCH_RIDES_FAIL';
export const FETCH_RIDES_SUCCESS = 'FETCH_RIDES_SUCCESS';



export const GET_USER_START = "GET_USER_START";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";


