//NORMAL AUTHENTICATION
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// FACEBOOK AUTHENTICATION
export const FACEBOOK_AUTH_START = 'FACEBOOK_AUTH_START';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';

// CAR ACTIONS
export const CAR_ADD_START = 'CAR_ADD_START';
export const CAR_ADD_FAIL = 'CAR_ADD_FAIL';
export const CAR_ADD_SUCCESS = 'CAR_ADD_SUCCESS';



export const GET_USER_START = "GET_USER_START";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";


