//NORMAL AUTHENTICATION
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


// FACEBOOK AUTHENTICATION
export const FACEBOOK_AUTH_START = 'FACEBOOK_AUTH_START';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';

// RIDES ACTIONS
export const FETCH_RIDES_START = 'FETCH_RIDES_START';
export const FETCH_RIDES_FAIL = 'FETCH_RIDES_FAIL';
export const FETCH_RIDES_SUCCESS = 'FETCH_RIDES_SUCCESS';


// SINGLE RIDE ACTIONS
export const FETCH_RIDE_START = 'FETCH_RIDE_START';
export const FETCH_RIDE_FAIL = 'FETCH_RIDE_FAIL';
export const FETCH_RIDE_SUCCESS = 'FETCH_RIDE_SUCCESS';


// SOCKET CONNECTION TYPES
export const WS_CONNECT_START = 'WS_CONNECT';
export const WS_CONNECT_FAIL = 'WS_CONNECT_FAIL';
export const WS_CONNECT_SUCCESS = 'WS_CONNECT_SUCCESS';

export const WS_DISCONNECT = 'WS_DISCONNECT';


export const WS_MESSAGE = 'WS_MESSAGE';
// REQUESTS THROUGH SOCKETS
export const GET_MY_REQUESTS = 'GET_MY_REQUESTS';
export const GET_RIDE_REQUESTS = 'GET_RIDE_REQUESTS';
export const JOIN_REQUEST = 'JOIN_REQUEST';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const DECLINE_REQUEST = 'DECLINE_REQUEST';
export const UNJOIN = 'UNJOIN';






export const GET_USER_START = "GET_USER_START";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";


